### ISSUE TITLE
Explicitly namespace OS-specific definitions

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang-nursery/libc#18]
There are reexports at the top level that are only available in Unix or Windows:

```rust
#[cfg(unix)] pub use consts::os::sysconf::*;

#[cfg(unix)] pub use funcs::posix88::mman::*;
#[cfg(unix)] pub use funcs::posix88::dirent::*;
#[cfg(unix)] pub use funcs::posix88::net::*;
#[cfg(unix)] pub use funcs::posix01::stat_::*;
#[cfg(unix)] pub use funcs::posix01::unistd::*;
#[cfg(unix)] pub use funcs::posix01::resource::*;


#[cfg(windows)] pub use funcs::extra::kernel32::*;
#[cfg(windows)] pub use funcs::extra::winsock::*;
#[cfg(windows)] pub use funcs::extra::msvcrt::*;
```

For clarity, and following the convention in `std`, these are better exported for public use in explicitly OS-specific modules `os::unix` and `os::windows`, and the top-level reexports deprecated.

**Comment by alexcrichton** [comment]
Thanks for the report! This repo is actually currently slated for a revamp, as detailed in an RFC: https://github.com/rust-lang/rfcs/pull/1291. The intention is to slate this library as platform-specific by default rather than platform-agnostic by default, but comments on the RFC are always welcome!
