### ISSUE TITLE
fd_set has private fields

### ISSUE THREAD

**Issue by sfackler** [rust-lang-nursery/libc#36]
http://rust-lang-nursery.github.io/libc/x86_64-unknown-linux-gnu/libc/struct.fd_set.html

**Comment by thibault-ml** [comment]
I was having this issue yesterday. I ended up having to use malloc (which isn't great). It would be nice to have a `new` method, or a least a function that returns an already initialised `fd_set`.

I don't think the fields should be public.

**Comment by alexcrichton** [comment]
Oh for initialization I'd recommend using `mem::uninitialized` or `mem::zeroed` followed by a `FD_ZERO`, the other macros like `FD_SET` and whatnot allow manipulation of the bits (note that this is the same interface exposed to C).

I'd be fine making the fields public, but I don't think they're currently correct for all platforms, so that'd have to be figured out first.

**Comment by alexcrichton** [comment]
I'm gonna close this for now as it's fine to make public, it just needs some legwork to figure out what the definitions are on each platform.
