### ISSUE TITLE
build.rs should be used

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/libc#69]
We should be using build.rs to link to the relevant external libraries instead of using `#[link] extern{}` thing.

**Comment by alexcrichton** [comment]
Right now the standard library isn't using Cargo so this'd end up just making that more painful than it needs to be. Otherwise if the names aren't changing across platforms and there's no need to override (as is true for this library), then `#[link]` is the same as a build script.

Once the standard library moves to Cargo we can try to explore this, but I don't think it's critical for now.
